Merge library to development
Blasco9/Library-JS pull request #1
Opened 2020-08-11 04:00 UTC by Blasco9

In this branch, we:
- Created the HTML index
- Created the styles for the page
- Designed the logic responsible for creating, removing and updating books
- Updated the README file

2020-08-12 12:56 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi team :hand: 
Awesome job so far :clap: 
But we need to work on some improvements before merging this PR.

- [x] Right it is possible to create a book without filling any information in the form. We need to fix that and make it possible to create books only after giving the required information: `title`, `author`, `page`.

- [x] It should not be possible to create books with a negative number of pages, like `-150`

- [x] We can improve the user experience from your application by adding headers to each book, to inform what is the `title`, what is the `author` and the `pages`. I agree that the current approach it's pretty intuitive, but some users may not think the same way.

Please kindly submit for code review again after making these changes.
Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**

2020-08-12 12:56 UTC, Torres-ssf commented on README.md
>  [Live Demo Link](https://livedemo.com)
- [ ] The live demo link is broken :cry: . We need to fix that :smile:

2020-08-13 12:53 UTC, shshamim63 approved these changes
## :100: Approved
___
Hi @Blasco9 and @Ashah15 :wave: 
Congratulation, you have successfully completed this project :clap: , nothing is blocking me from approving this project. You can go ahead.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-08-13 12:53 UTC, shshamim63 commented on index.html
> +        <input class="book-pages" name="pages" type="number" />
[Optional]
Usually, a book does not have any negative page numbers. So allowing a user to do that is against the default convention. So you can control this scenario, by updating the input field in the following way,
```html
<input class="book-pages" name="pages" type="number" min="0"  />
```

2020-08-13 13:58 UTC, merged